package com.sum.poc.server.model;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.sum.poc.server.adapters.DateAdapter;// Generated Dec 4, 2016 8:08:44 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Regions generated by hbm2java
 */
@Entity
@Table(name="REGIONS"
)
@XmlRootElement(name="regions")
@XmlAccessorType(XmlAccessType.FIELD)
public class Regions extends com.sum.poc.server.model.POCEntity   implements java.io.Serializable {


     private BigDecimal regionId;
     private String regionName;
@XmlTransient
     private Set<Countries> countrieses = new HashSet<Countries>(0);

    public Regions() {
    }

	
    public Regions(BigDecimal regionId) {
        this.regionId = regionId;
    }
    public Regions(BigDecimal regionId, String regionName, Set<Countries> countrieses) {
       this.regionId = regionId;
       this.regionName = regionName;
       this.countrieses = countrieses;
    }
   
     @Id 

    
    @Column(name="REGION_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(BigDecimal regionId) {
        this.regionId = regionId;
    }

    
    @Column(name="REGION_NAME", length=25)
    public String getRegionName() {
        return this.regionName;
    }
    
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="regions")
    public Set<Countries> getCountrieses() {
        return this.countrieses;
    }
    
    public void setCountrieses(Set<Countries> countrieses) {
        this.countrieses = countrieses;
    }




}


