package com.sum.poc.server.model;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.sum.poc.server.adapters.DateAdapter;// Generated Dec 4, 2016 8:08:44 AM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAuthorization generated by hbm2java
 */
@Entity
@Table(name="USER_AUTHORIZATION"
)
@XmlRootElement(name="userauthorization")
@XmlAccessorType(XmlAccessType.FIELD)
public class UserAuthorization extends com.sum.poc.server.model.POCEntity   implements java.io.Serializable {


     private BigDecimal userRoleId;
@XmlTransient
     private UserAuthentication userAuthentication;
     private String role;

    public UserAuthorization() {
    }

	
    public UserAuthorization(BigDecimal userRoleId) {
        this.userRoleId = userRoleId;
    }
    public UserAuthorization(BigDecimal userRoleId, UserAuthentication userAuthentication, String role) {
       this.userRoleId = userRoleId;
       this.userAuthentication = userAuthentication;
       this.role = role;
    }
   
     @Id 

    
    @Column(name="USER_ROLE_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(BigDecimal userRoleId) {
        this.userRoleId = userRoleId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID")
    public UserAuthentication getUserAuthentication() {
        return this.userAuthentication;
    }
    
    public void setUserAuthentication(UserAuthentication userAuthentication) {
        this.userAuthentication = userAuthentication;
    }

    
    @Column(name="ROLE", length=50)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


